export default {
  docsSidebar: [
    "README",
    { type: "category", label: "Get started", items: [{ type: "autogenerated", dirName: "guides" }] },
    { type: "category", label: "API", items: [{ type: "autogenerated", dirName: "api" }] },
  ],
};
